package: scikit-rf
user: scikit-rf

install:
  - conda config --add channels scikit-rf



platform:
  - linux-64
  #- linux-32
  - osx-64
  #- win-32
  - win-64
engine:
  - python=2.7
  - python=3.3
script:
  - conda build conda.recipe --quiet

iotimeout: 600

build_targets: conda

notifications:
  email:
    recipients: ['alexanderarsenovic@gmail.com']
