channels:
    - conda-forge
dependencies:
    - python=3.5
    - pandas
    - setuptools
    - ipython
    - numpy
    - scipy
    - matplotlib
    - mock
    - nose
    - future
    - pandoc
    - nbconvert=4.2
    - ipykernel
    - ipywidgets
    - xlwt
    - xlrd
    - nbsphinx
    - pip:
        - python-ivi
        - PyVisa
        #- git+https://github.com/arsenovic/nbsphinx.git@master
